### ISSUE TITLE
tinc service start and fail silently

### ISSUE THREAD

**Issue by zedtux** [EugenMayer/chef-tinc-cookbook#11]
I finally got tinc deployed on a machine but no net interfaces.

I search a on the internet and found [this thread](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841052) which explains that you have to enable the service for the network to solve the issue.

Doing `systemctl status tinc@<network_name>` and then restarting the `tinc` service solved my issue.

**Comment by EugenMayer** [comment]
We should have this in our cookbook already afair

**Comment by zedtux** [comment]
Actually this is done with the `default` network, but when using a different name, then it's not.

In kitchen I can see the `tinc@default` service enabled, but on my box, with a different name than `default` it wasn't enable.

**Comment by zedtux** [comment]
Ah, `node['lsb']['codename']` is `nil` on my box.

I had this issue too in a cookbook, I solved it by parsing the `/etc/os-release` file which is the only place where it is _sur_ to be found.

**Comment by EugenMayer** [comment]
Afaik this is due to the package lsb-release or similar not being installed - I am on vacation right now and cannot check this deeper

**Comment by zedtux** [comment]
Yes, this is the reason of this issue. On my boxes the lsb-release package is not installed by default so that why I managed it like that.

Enjoy your vacations and let's see that when you're back :)

**Comment by EugenMayer** [comment]
Well if we depend on lsb release we should install it. Any chance to hg have you pr this - it's your find, your credit

**Comment by zedtux** [comment]
My PR is _solving_ this issue by parsing the `/etc/os-release` file so this issue is fixed as soon as you merge it.

Otherwise, if you really prefer having the lsb package, I can do it for sure, just wanted to highlight the existing fix in the PR.
