### ISSUE TITLE
Avahi fails when network name is too long - should add a warning?

### ISSUE THREAD

**Issue by zedtux** [EugenMayer/chef-tinc-cookbook#13]
I was using the network name `kubernetes-staging` and got the issue that Avahi never get an IPv4 address.

I found this ticket ubuntu issue [avahi-autoipd fails because network interface name is too long](https://bugs.launchpad.net/ubuntu/+source/avahi/+bug/1666900) so I tried to rename my network to `k8sstg` and now it works.

I have noticed that the network name `kubernetes-staging` was always truncated to `kubernetes-stag` which has a length of 15, so we could add a warning message when the network name is longer than 15.

**Comment by EugenMayer** [comment]
That's a very nice find - and ugly indeed. We should probably implement an handling on our side, print the issue and write a TODO to recheck with the above issue
