### ISSUE TITLE
Reload Ohai network plugin

### ISSUE THREAD

**Issue by zedtux** [EugenMayer/chef-tinc-cookbook#15]
I figured out what is the issue I mentioned in #14, and it relates to Ohai.

In my Kubernetes cookbook I'm using `node['network']['interfaces']` and this cookbook is not reloading them after having started tinc.

From [the Ohai resource documentation](https://docs.chef.io/ohai.html#ohai-resource):

> Use the ohai resource to reload the Ohai configuration on a node. This allows recipes that change system attributes (like a recipe that adds a user) to refer to those attributes later on during a Chef Infra Client run.

IMHO this cookbook should trigger a reload of the Ohai `network` plugin.

**Comment by EugenMayer** [comment]
Does this mean a new dependency?do we expect side effects / should we add this as a side dish?

**Comment by zedtux** [comment]
> Does this mean a new dependency?

No, no new dependency.

You just need to add a `ohai` resource and notify it for reloading the `network` plugin. Actually, while waiting for your answer, I did it in my Kubernetes cookbook that runs after yours. You can see it [here](https://gitlab.com/pharmony/kubeadm-cookbook/blob/master/recipes/master.rb#L9).

> do we expect side effects / should we add this as a side dish?

The side effect is really limited as it immediately updates the Ohai data instead of doing it on the next converge.

A kind of workaround of this issue is to bootstrap the node, it will fail as the network interface will be missing, then converge it and then the new network interface is listed so that the converge passes.

**Comment by EugenMayer** [comment]
Well that sounds convinient, then just call the OHAI reload and we are set for that - thank you for looking into that

**Comment by zedtux** [comment]
Let's do this in a PR after the big one is merged 😉

**Comment by EugenMayer** [comment]
The big brother just went on stage :)

**Comment by zedtux** [comment]
I'll prepare the next PR for this issue. It will be much more smaller, I promesse 😉.
