### ISSUE TITLE
Tinc service reload doesn't seem to be enough when adding host files

### ISSUE THREAD

**Issue by zedtux** [EugenMayer/chef-tinc-cookbook#16]
I had the issue that my nodes weren't able to communicate together until I restart the tinc service, which makes me thinking that [reloading the service](https://github.com/EugenMayer/chef-tinc-cookbook/blob/master/recipes/default.rb#L120) doesn't seem to be enough.

I'm using my branch to report this issue, but it shouldn't be related as I haven't changed the service restart/reload.

Here is my step-by-step :

1. Bootstrap a node with tinc
2. Bootstrap a second node with tinc
3. Converge the first node so that it has the second node tinc host file
4. Ssh to one of the nodes, and try to ping the other one:
    ```
    $ ping 10.0.0.111
    PING 10.0.0.111 (10.0.0.111) 56(84) bytes of data.
    From 10.0.0.111 icmp_seq=1 Destination Net Unknown
    From 10.0.0.111 icmp_seq=2 Destination Net Unknown
    ```
5. Check the status:
    ```
    $ systemctl status tinc@<network name>
    ...
    tincd[25661]: Got bad ID from <unknown> (XXX.XX.XXX.XX port 44224): invalid name
    tincd[25661]: Error while processing ID from <unknown> (XXX.XX.XXX.XX port 44224)
    tincd[25661]: Cannot open config file /etc/tinc/<network name>/hosts/<node hostname>: No such file or directory
    ```
6. Restart the service with `systemctl restart tinc@<network name>`
7. Try again to ping and it works.

**Comment by EugenMayer** [comment]
Well if you can reproduce that, please check the routes / list them here - maybe those are not applied correctly depending on the kill signal?

**Comment by EugenMayer** [comment]
Oh I see, you already investigated that, sorry. The question is, afair our test should break too but they don't - maybe that's depending on the linux distribution used and tincs systems integration there - what OS did you use?

**Comment by zedtux** [comment]
I'm using a Debian Stretch box.

> our test should break too but they don't

You are very right, but I'm not sure they're reproducing the given step by step. I need to check, but as far as I know all is setup in one shot, so they have the boot/reboot benefit of the tinc service, while in my case, after that initial boot of the tinc service, I'm _just_ adding a new tinc host file, which triggers a `reload`, not a `restart` and here is the issue.

We should check that in our test suite, the case of **only adding a new host file and therefore executing a simple service reload** is covered.

**Comment by zedtux** [comment]
@EugenMayer I have to solve this issue now as it prevents me from having a perfect provisioning.

From what angle would you like I'm doing it? Should I spent plenty of time to get it highlighted by the tests, or should I just fix it?

In the case you ask me "to get it highlighted by the tests", what would be the benefit 'cause we're only speaking of restarting the service.
The impact should be very limited, even do it looks weird to have to restart the service.

Thank you.

**Comment by EugenMayer** [comment]
I would absolutely go the pragmatic way -we are restart the service when we change the network layout / configuration. I cannot see how this is 

 - a task we do often ( each chef run )
 - it suprises the user of that receipe by any means

So to be frank, i would just fix it, not really nail it with tests for that purpose - as you mentioned, i cannot see a big benefit in that

**Comment by zedtux** [comment]
Thank you, I'll open the PR soon
