### ISSUE TITLE
Host pubkey could be undefined in some cases

### ISSUE THREAD

**Issue by zedtux** [EugenMayer/chef-tinc-cookbook#19]
It happened to me many times where a node JSON file would miss the `pubkey` from my chef repo.

This happens when the bootstrap/converge fails.

I'd like to open a PR which adds the `pubkey` when it is missing from the existing RSA file, do you agree?

**Comment by EugenMayer** [comment]
I am really not sure i can follow you on this

you mean

https://github.com/EugenMayer/chef-tinc-cookbook/blob/master/recipes/default.rb#L171

considering 

https://github.com/EugenMayer/chef-tinc-cookbook/blob/master/recipes/default.rb#L152

which only selects why pubkey is set, iam not sure why it ever would be missing?

**Comment by zedtux** [comment]
Sorry for not being clear enough.

No, I'm talking about [this line](https://github.com/EugenMayer/chef-tinc-cookbook/blob/master/recipes/default.rb#L125).

It works perfectly when the bootstrap of a node succeed, but in the case of a failure, the `pubkey` is not saved, but the RSA files are present on the disk, which makes this cookbook to not run the block again on the next bootstrap/converge.

Not regenerating the key, while it is present, is perfect, but not updating the `pubkey` is the problem.
IMHO the `pubkey` should always reflect the content of the RSA pub key.

**Comment by zedtux** [comment]
I've created the PR, maybe it will be much more understandable for you.

**Comment by EugenMayer** [comment]
Sorry i missunderstood - got you on this, makes pefect sense!
