### ISSUE TITLE
Create 0.2.0 release

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/chef-tinc-cookbook#2]

**Comment by mrvovanness** [comment]
@EugenMayer  when new version will be released on chef supermarket?

**Comment by EugenMayer** [comment]
sorry, kind of busy, thanks for bumping, trying to get it done ASAP

**Comment by EugenMayer** [comment]
sorry for the huge delay. Decided to release it as 0.1.10 but it is at least out now! Thanks for being patient
