### ISSUE TITLE
Enable tun/tap network interface when missing

### ISSUE THREAD

**Issue by zedtux** [EugenMayer/chef-tinc-cookbook#23]
I have the case where the hosts provided by a provider are missing the tun/tap files (even no `/dev/net` folder).

From an issue I've opened, they solved my issue by asking me to run the following commands:

```
mkdir /dev/net
mknod /dev/net/tun c 10 200
```

I would add them to this cookbook and I have 2 suggestions:

1. Detect if the `/dev/net/tun` file exist or not, then run the commands
2. Detect if the `/dev/net/tun` file exist and show a warning by default, otherwise, via an attribute, allow to run the commands

What's your input about this Eugen?

**Comment by EugenMayer** [comment]
I am not sure what we are fixing here, is this a PaaS / IaaS provider issue which we are actually fixing using the cookbook - or is a linux distribution issue?

I have never had to create those interfaces manually yet, so why is this needed in this case and what official documentation is for that?

```
mkdir /dev/net
mknod /dev/net/tun c 10 200
```

neither of these commands i have ever used under Linux or Freebsd, so why your provider requires that?

If there are no good facts about that is needed in general, i what error are we throwing if that is missing? If this error is already good ( tells what is missing ) i would rather do not change anything in this cookbook but rather suggest you create a new cookbook ( wrapper cookbook ) called "provider-xyz-iaas-myapp" and there you include all your recipes and add folders and things you need in addition to harmonize the instance to a "normal linux box"

**Comment by zedtux** [comment]
I completely agree with you.

The provider is using OpenVZ, don't know if this could be the reason for this lack of `/dev/net` stuff.

To answer the "why", maybe [this](https://help.skysilk.com/support/solutions/articles/9000136471-how-to-enable-tun-tap-on-linux-vps-with-skysilk) give an explanation (See "Why do I need to do this?"), so could be for security reason ... :man_shrugging:.

Anyway I think you're right, creating a wrapper cookbook is a much more clever approach.

Let's close this issue then

**Comment by EugenMayer** [comment]
The link you refer to is a ENV based issue - VPS / openvz - this cookbook should not handle normalizing those ENVs to a usual linux env - so as you already opted in for, go for a wrapper cookbook here. Thanks

**Comment by zedtux** [comment]
Thank you Eugen for your comment.
