### ISSUE TITLE
Useless tinc restarts

### ISSUE THREAD

**Issue by zedtux** [EugenMayer/chef-tinc-cookbook#33]
I noticed month ago already that the tinc service is restarted **each time** I converge a node, which doesn't look right but not hurting, right?

Well, until I'm facing issues with my Kubernetes cookbook where nodes aren't able to join masters, and I guess because of the services restarting (when tinc restarts, I assume changes in its config, therefore I'm restarting services in my cookbook in order to be sure to have the right IP address).

I first fixed the issues in my cookbook where `keepalived` was restarting each time I'm converging a node and thanks to the help from the sous-chef community I was able to solve it, and here is how:

Mainly I was writing a file using a template passing arguments at compile time (instead of execution time) which makes chef seeing changes were there aren't.

Something like that:

```ruby
keepalived_vrrp_instance 'kubernetes-vip' do
  authentication    auth_type: 'PASS', auth_pass: keepalived_password
  interface         node['kubeadm']['interface']
  master            keepalived_master
  notify            keepalived_notify_script_path
  priority          keepalived_master ? 110 : 100
  track_script      %w[haproxy-check]
  unicast_src_ip    node['kubeadm']['keepalived']['unicast_src_ip']
  unicast_peer      node['kubeadm']['keepalived']['unicast_peer']
  virtual_ipaddress Array(node['kubeadm']['master_ip_address'])
  virtual_router_id keepalived_router_id

  notifies :restart, 'service[keepalived]', :delayed
end
```

has been changed like that:

```ruby
keepalived_vrrp_instance 'kubernetes-vip' do
  authentication auth_type: 'PASS',
                 auth_pass: lazy { node.run_state['keepalived_password'] }
  interface node['kubeadm']['interface']
  master(lazy { node.run_state['keepalived_master'] })
  notify keepalived_notify_script_path
  priority(lazy { node.run_state['keepalived_master'] ? 110 : 100 })
  track_script %w[haproxy-check]
  unicast_src_ip node['kubeadm']['keepalived']['unicast_src_ip']
  unicast_peer node['kubeadm']['keepalived']['unicast_peer']
  virtual_ipaddress Array(node['kubeadm']['master_ip_address'])
  virtual_router_id(lazy { node.run_state['keepalived_router_id'] })

  notifies :restart, 'service[keepalived]', :delayed
end
```

The variables are filled in from a `ruby_block`, then `lazy` loaded, which makes chef taking values at run time, solving the changes detection issue.

This cookbook is suffering of the same trouble when it comes to generate the host files:

```
* template[/etc/default/tinc] action create[2020-07-16T14:34:28+02:00] INFO: Processing template[/etc/default/tinc] action create (tincvpn::default line 147)
(up to date)
* directory[/etc/tinc/k8sstg] action create[2020-07-16T14:34:28+02:00] INFO: Processing directory[/etc/tinc/k8sstg] action create (tincvpn::default line 195)
(up to date)
* directory[/etc/tinc/k8sstg/hosts] action create[2020-07-16T14:34:28+02:00] INFO: Processing directory[/etc/tinc/k8sstg/hosts] action create (tincvpn::default line 196)
(up to date)
* execute[generate-k8sstg-keys] action run[2020-07-16T14:34:28+02:00] INFO: Processing execute[generate-k8sstg-keys] action run (tincvpn::default line 238)
(skipped due to not_if)
* template[/etc/tinc/k8sstg/hosts/east_stg_mst_1] action create[2020-07-16T14:34:28+02:00] INFO: Processing template[/etc/tinc/k8sstg/hosts/east_stg_mst_1] action create (tincvpn::default line 251)
[2020-07-16T14:34:28+02:00] INFO: template[/etc/tinc/k8sstg/hosts/east_stg_mst_1] backed up to /var/chef/backup/etc/tinc/k8sstg/hosts/east_stg_mst_1.chef-20200716143428.903837
[2020-07-16T14:34:28+02:00] INFO: template[/etc/tinc/k8sstg/hosts/east_stg_mst_1] removed backup at /var/chef/backup/etc/tinc/k8sstg/hosts/east_stg_mst_1.chef-20200715152619.410754
[2020-07-16T14:34:28+02:00] INFO: template[/etc/tinc/k8sstg/hosts/east_stg_mst_1] updated file contents /etc/tinc/k8sstg/hosts/east_stg_mst_1

- update content in file /etc/tinc/k8sstg/hosts/east_stg_mst_1 from 3c0804 to dc2d59
--- /etc/tinc/k8sstg/hosts/east_stg_mst_1 2020-07-16 14:03:12.992859063 +0200
+++ /etc/tinc/k8sstg/hosts/.chef-east_stg_mst_120200716-22966-coz1s3 2020-07-16 14:34:28.898824655 +0200
@@ -2,7 +2,6 @@
Cipher=aes-256-cbc
Digest=sha256

-Subnet = 10.0.0.223/32


-----BEGIN RSA PUBLIC KEY-----
* ruby_block[publish-public-key-k8sstg] action run[2020-07-16T14:34:28+02:00] INFO: Processing ruby_block[publish-public-key-k8sstg] action run (tincvpn::default line 263)
[2020-07-16T14:34:28+02:00] INFO: ruby_block[publish-public-key-k8sstg] called

- execute the ruby block publish-public-key-k8sstg
* template[/etc/tinc/k8sstg/tinc-up] action create[2020-07-16T14:34:28+02:00] INFO: Processing template[/etc/tinc/k8sstg/tinc-up] action create (tincvpn::default line 282)
(up to date)
* template[/etc/tinc/k8sstg/tinc-down] action create[2020-07-16T14:34:28+02:00] INFO: Processing template[/etc/tinc/k8sstg/tinc-down] action create (tincvpn::default line 282)
(up to date)
* template[/etc/tinc/k8sstg/hosts/east_stg_mst_1] action create[2020-07-16T14:34:28+02:00] INFO: Processing template[/etc/tinc/k8sstg/hosts/east_stg_mst_1] action create (tincvpn::default line 343)
[2020-07-16T14:34:29+02:00] INFO: template[/etc/tinc/k8sstg/hosts/east_stg_mst_1] backed up to /var/chef/backup/etc/tinc/k8sstg/hosts/east_stg_mst_1.chef-20200716143429.010112
[2020-07-16T14:34:29+02:00] INFO: template[/etc/tinc/k8sstg/hosts/east_stg_mst_1] removed backup at /var/chef/backup/etc/tinc/k8sstg/hosts/east_stg_mst_1.chef-20200715155801.408448
[2020-07-16T14:34:29+02:00] INFO: template[/etc/tinc/k8sstg/hosts/east_stg_mst_1] updated file contents /etc/tinc/k8sstg/hosts/east_stg_mst_1

- update content in file /etc/tinc/k8sstg/hosts/east_stg_mst_1 from dc2d59 to 3c0804
--- /etc/tinc/k8sstg/hosts/east_stg_mst_1 2020-07-16 14:34:28.898824655 +0200
+++ /etc/tinc/k8sstg/hosts/.chef-east_stg_mst_120200716-22966-camq8f 2020-07-16 14:34:29.006824080 +0200
@@ -2,6 +2,7 @@
Cipher=aes-256-cbc
Digest=sha256

+Subnet = 10.0.0.223/32


-----BEGIN RSA PUBLIC KEY-----
[2020-07-16T14:34:29+02:00] INFO: template[/etc/tinc/k8sstg/hosts/east_stg_mst_1] not queuing delayed action restart on service[tinc] (delayed), as it's already been queued
[2020-07-16T14:34:29+02:00] INFO: template[/etc/tinc/k8sstg/hosts/east_stg_mst_1] not queuing delayed action reload on ohai[reload network] (delayed), as it's already been queued
* template[/etc/tinc/k8sstg/hosts/east_stg_mst_2] action create[2020-07-16T14:34:29+02:00] INFO: Processing template[/etc/tinc/k8sstg/hosts/east_stg_mst_2] action create (tincvpn::default line 343)
(up to date)
* template[/etc/tinc/k8sstg/tinc.conf] action create[2020-07-16T14:34:29+02:00] INFO: Processing template[/etc/tinc/k8sstg/tinc.conf] action create (tincvpn::default line 368)
(up to date)
* service[tinc@k8sstg] action enable[2020-07-16T14:34:29+02:00] INFO: Processing service[tinc@k8sstg] action enable (tincvpn::default line 383)
(up to date)
```

As you can see from those logs, while the `/etc/default/tinc`, `/etc/tinc/k8sstg` and `/etc/tinc/k8sstg/tinc.conf` files are seen as already up to date, the host file `/etc/tinc/k8sstg/hosts/east_stg_mst_1` is seen as updated (removing the `Subnet` line, then adding it again).

_Note that the fact that the second host file `/etc/tinc/k8sstg/hosts/east_stg_mst_2` is seen as up to date is quite confusing me._

I think that moving the entire recipe in `ruby_block`(s) should solve this issue.

**Comment by EugenMayer** [comment]
Very interesting catch and for sure relevant, since we are talkinga bout a VPN service and regular restarts can interrupt any service.

Are you up to provide a PR for that? Right now it feels like you seem to have a far better grip on the chef lifecycle issue in this regard, a far better understanding then i have

**Comment by zedtux** [comment]
I'm working on it, but not very actively as I already have a WIP PR where I need to figure out how to pass environments to Kitchen CI.

**Comment by zedtux** [comment]
I really have to solve this one as those Tinc restarts are breaking my Kubernetes clusters.

[Restating Tinc (but also network services) destroys some network interfaces](https://github.com/coreos/flannel/issues/869), like its own, but also a Kubernetes one that make pods isolated one the defective node.

But this needs some testing as I remember having troubles with `reload`. Anyways, after that issue, I will do #31 as it is a small one, and then version 1.1.0 will be finished on my side.

**Comment by EugenMayer** [comment]
Yes i imagine that if you keep the fleet up2date all the time with chef and tinc is restarted, there are a lot of side effects.  

When are restart needed:

a) first / initial configuration
b) critical reconfiguration which would make the client incompatible with the fleet ( like certificates, hostnames..what else )
c) ?

While a) can be easily optimized and isolated, b) is a lot harder and means it could happen anytime.  This means :+1: 

- we need to define which data attributes we consider to force a restart
- are there several groups of attributes ( group1: mmidiate restart needed, group2: later restart possible, like scheduled)

Maybe, by segmenting and defining the problem we can identify the critical / hard parts and can work around those if needed or happen to notice we do not need restarts in y/x/y.
