### ISSUE TITLE
Host names with hyphens will not work.

### ISSUE THREAD

**Issue by daveallen** [EugenMayer/chef-tinc-cookbook#4]
Since tinc only allows letters, numbers and underscores in a name (which should be changed by them) any hostnames with a hyphen does not work.  I use staging- for my staging instances. And underscores are not allowed in domain names.  Can you think of a way around this?

**Comment by EugenMayer** [comment]
well feel free to debug this anytime - i am not sure where it fails

**Comment by daveallen** [comment]
Here is a pull request to solve this one.
https://github.com/EugenMayer/chef-tinc-cookbook/pull/5

**Comment by EugenMayer** [comment]
thanks for the contribution, good catch actually!
