### ISSUE TITLE
Automatic host name

### ISSUE THREAD

**Issue by zedtux** [EugenMayer/chef-tinc-cookbook#8]
I'm a little bit confused about the host name attribute to be set manually as it could be retrieved with [ohai](https://docs.chef.io/ohai.html) or I guess there should be a way to get the `--node-name` value from the `bootstrap` or `converge` chef command.

I'm using a Policyfile where I would expect to give the network name where all the nodes for that policy should join.

Do you see something wrong here? If so, could you please explain me what's wrong? Thank you

**Comment by EugenMayer** [comment]
I am not really sure how this thing worked out, I think it could be a hen/egg issue at some point. When you initially provision a box and the semantic hostname is yet not applied I recall that the tinc setup goes wrong in the same run.

If you want to introduce this, be sure to use the kitchen tests to endure it works. Also we would need a Boolean attribute to turn this feature on, off by default ( for now )

**Comment by zedtux** [comment]
I'll give it a try, thank you for your input.

Are you using Policyfile ?
I would go for the network name defined in the policy group so that all the nodes within the same policy group would be in the same network name, no matter its hostname.

**Comment by EugenMayer** [comment]
Nope not using it (for now)
